project:
  type: website
  output-dir: docs
website:
  site-url: /
  repo-url: https://github.com/lf2l
  #repo-actions: [edit, issue]
  title: "LF2L"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: news.qmd
        text: News
      - href: community.qmd
        text: Community  
      - href: project.qmd
        text: Projects
      - href: team.qmd
        text: Team

      - text: Langes      
        menu:
          - text: french
            url:  fr/
          - text: Espanol
            url:  es/

  page-footer:
    background: light
    left: "Copyright 2023, ERPI Laboratory <br> Powered by [Quarto](https://quarto.org/) v1.3.24"
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twi
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



babelquarto:
  languagecodes:
  - name: fr
    text: "Français"
  - name: es
    text: "Español"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['fr', 'es']

title-fr: Lorraine Fab Living Lab
title-es: Lorraine Fab Living 
description-es: description in es
description-fr: description in fr
author-es: author in es
author-fr: author in fr
lang: en


