project:
  type: website
  output-dir: docs
website:
  favicon: assets/favicon.png
  bread-crumbs: true
  reader-mode: false
  open-graph: true
  site-url: https://fabbiocrux.github.io/LF2L-V2/
  repo-url: https://github.com/lf2l
  #repo-actions: [edit, issue]
  title: "LF2L"
  navbar:
    background: primary
    foreground: white
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/company/102623341/        
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
#      - href: news.qmd
      - href: project.qmd      
      - href: publications.qmd      
      - href: community.qmd
      - href: team.qmd

  page-footer:
    background: light
    left: "Copyright 2024, ERPI et ENSGSI <br> Powered by [Quarto](https://quarto.org/) v1.3.24"
    center: 
      - icon: github
        href: https://github.com/
      - icon: instagram
        href: /        
      - icon: linkedin
        href: /
      - icon: twitter
        href: /
    # right: 
    #   - icon: github
    #     href: https://github.com/
    #   - icon: instagram
    #     href: /        
    #   - icon: linkedin
    #     href: /
    #   - icon: twitter
    #     href: /
        
format:
  html:
    page-layout: full
    theme:
      - cosmo
      - styles.scss
    toc: true



babelquarto:
  languagecodes:
  - name: fr
    text: "Français"
  - name: en
    text: "English"    
  - name: es
    text: "Español"
  mainlanguage: 'fr'
  languages: ['en', 'es']

title-en: LF2L
title-es: LF2L
description-en: description in fr
description-es: description in es
author-en: author in fr
author-es: Autores
lang: fr


