project:
  type: website
  output-dir: docs
website:
  favicon: assets/favicon.png
  bread-crumbs: true
  reader-mode: true
  site-url: https://fabbiocrux.github.io/LF2L-V2/
  repo-url: https://github.com/lf2l
  #repo-actions: [edit, issue]
  title: "LF2L"
  navbar:
    background: primary
    foreground: white
    right:
      - href: index.qmd
        text: Home
      - href: news.qmd
      - href: community.qmd
      - href: project.qmd
      - href: team.qmd


  page-footer:
    background: light
    left: "Copyright 2023, ERPI Laboratory <br> Powered by [Quarto](https://quarto.org/) v1.3.24"
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twi
        
format:
  html:
    page-layout: full
    theme:
      - cosmo
      - styles.scss
    toc: true



babelquarto:
  languagecodes:
  - name: fr
    text: "Français"
  - name: es
    text: "Español"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['fr', 'es']

title-fr: LF2L
title-es: LF2L
description-es: description in es
description-fr: description in fr
author-es: author in es
author-fr: author in fr
lang: en


